import 'layout_data.dart';
import 'tile_data.dart';

class LevelDefinition {
  final int id;
  final String name;
  final int boardRows;
  final int boardCols;
  final int tileCount; // must equal layout.length
  final List<String> tileIds;
  final int unlockRequirement;
  final List<int> starThresholds;
  final List<TilePosition> layout;

  const LevelDefinition({
    required this.id,
    required this.name,
    required this.boardRows,
    required this.boardCols,
    required this.tileCount,
    required this.tileIds,
    required this.unlockRequirement,
    required this.starThresholds,
    required this.layout,
  });
}

List<String> _tileIdsForPairs(int pairCount) =>
    kTileIds.take(pairCount).toList(growable: false);

final List<LevelDefinition> kLevels = [
  LevelDefinition(
    id: 1,
    name: 'First Look',
    boardRows: 4,
    boardCols: 6,
    tileCount: 28,
    tileIds: _tileIdsForPairs(14),
    unlockRequirement: 0,
    starThresholds: const [700, 1100, 1400],
    layout: level4Layout,
  ),
  LevelDefinition(
    id: 2,
    name: 'New Roots',
    boardRows: 5,
    boardCols: 6,
    tileCount: 36,
    tileIds: _tileIdsForPairs(18),
    unlockRequirement: 1,
    starThresholds: const [900, 1400, 1800],
    layout: level5Layout,
  ),
  LevelDefinition(
    id: 3,
    name: 'Council',
    boardRows: 5,
    boardCols: 7,
    tileCount: 44,
    tileIds: _tileIdsForPairs(22),
    unlockRequirement: 2,
    starThresholds: const [1100, 1750, 2200],
    layout: level7Layout,
  ),
  LevelDefinition(
    id: 4,
    name: 'Heritage',
    boardRows: 5,
    boardCols: 7,
    tileCount: 52,
    tileIds: _tileIdsForPairs(26),
    unlockRequirement: 3,
    starThresholds: const [1300, 2100, 2600],
    layout: level9Layout,
  ),
  LevelDefinition(
    id: 5,
    name: 'Legacy',
    boardRows: 5,
    boardCols: 8,
    tileCount: 60,
    tileIds: _tileIdsForPairs(30),
    unlockRequirement: 4,
    starThresholds: const [1600, 2600, 3200],
    layout: level11Layout,
  ),
  LevelDefinition(
    id: 6,
    name: 'Complete Set',
    boardRows: 6,
    boardCols: 7,
    tileCount: 68,
    tileIds: _tileIdsForPairs(34),
    unlockRequirement: 5,
    starThresholds: const [2000, 3200, 4000],
    layout: level13Layout,
  ),
  LevelDefinition(
    id: 7,
    name: 'New Symbols',
    boardRows: 6,
    boardCols: 8,
    tileCount: 72,
    tileIds: _tileIdsForPairs(36),
    unlockRequirement: 6,
    starThresholds: const [2200, 3500, 4300],
    layout: level14Layout,
  ),
  LevelDefinition(
    id: 8,
    name: 'Gathering',
    boardRows: 6,
    boardCols: 8,
    tileCount: 76,
    tileIds: _tileIdsForPairs(38),
    unlockRequirement: 7,
    starThresholds: const [2400, 3800, 4600],
    layout: level15Layout,
  ),
  LevelDefinition(
    id: 9,
    name: 'Deep Roots',
    boardRows: 6,
    boardCols: 8,
    tileCount: 80,
    tileIds: _tileIdsForPairs(40),
    unlockRequirement: 8,
    starThresholds: const [2600, 4100, 5000],
    layout: level16Layout,
  ),
  LevelDefinition(
    id: 10,
    name: 'Living Archive',
    boardRows: 6,
    boardCols: 9,
    tileCount: 84,
    tileIds: _tileIdsForPairs(42),
    unlockRequirement: 9,
    starThresholds: const [2800, 4400, 5400],
    layout: level17Layout,
  ),
  LevelDefinition(
    id: 11,
    name: 'Ancestral Map',
    boardRows: 7,
    boardCols: 9,
    tileCount: 88,
    tileIds: _tileIdsForPairs(44),
    unlockRequirement: 10,
    starThresholds: const [3000, 4700, 5800],
    layout: level18Layout,
  ),
  LevelDefinition(
    id: 12,
    name: 'Many Voices',
    boardRows: 7,
    boardCols: 9,
    tileCount: 92,
    tileIds: _tileIdsForPairs(46),
    unlockRequirement: 11,
    starThresholds: const [3200, 5000, 6200],
    layout: level19Layout,
  ),
  LevelDefinition(
    id: 13,
    name: 'Long Memory',
    boardRows: 7,
    boardCols: 10,
    tileCount: 96,
    tileIds: _tileIdsForPairs(48),
    unlockRequirement: 12,
    starThresholds: const [3400, 5300, 6600],
    layout: level20Layout,
  ),
  LevelDefinition(
    id: 14,
    name: 'Full Archive',
    boardRows: 7,
    boardCols: 10,
    tileCount: 102,
    tileIds: kTileIds,
    unlockRequirement: 13,
    starThresholds: const [3600, 5600, 7000],
    layout: level21Layout,
  ),
  LevelDefinition(
    id: 15,
    name: 'Open Courtyard',
    boardRows: 10,
    boardCols: 12,
    tileCount: 110,
    tileIds: _tileIdsForPairs(55),
    unlockRequirement: 14,
    starThresholds: const [3900, 6000, 7500],
    layout: level22Layout,
  ),
  LevelDefinition(
    id: 16,
    name: 'Wisdom House',
    boardRows: 10,
    boardCols: 12,
    tileCount: 118,
    tileIds: _tileIdsForPairs(59),
    unlockRequirement: 15,
    starThresholds: const [4200, 6400, 8000],
    layout: level23Layout,
  ),
  LevelDefinition(
    id: 17,
    name: 'Golden Stool',
    boardRows: 11,
    boardCols: 12,
    tileCount: 126,
    tileIds: _tileIdsForPairs(63),
    unlockRequirement: 16,
    starThresholds: const [4500, 6800, 8500],
    layout: level24Layout,
  ),
  LevelDefinition(
    id: 18,
    name: 'Shared Path',
    boardRows: 12,
    boardCols: 12,
    tileCount: 134,
    tileIds: _tileIdsForPairs(67),
    unlockRequirement: 17,
    starThresholds: const [4800, 7200, 9000],
    layout: level25Layout,
  ),
  LevelDefinition(
    id: 19,
    name: 'Sacred Grove',
    boardRows: 12,
    boardCols: 12,
    tileCount: 142,
    tileIds: _tileIdsForPairs(71),
    unlockRequirement: 18,
    starThresholds: const [5100, 7600, 9500],
    layout: level26Layout,
  ),
  LevelDefinition(
    id: 20,
    name: 'Elders Assembly',
    boardRows: 13,
    boardCols: 12,
    tileCount: 150,
    tileIds: _tileIdsForPairs(75),
    unlockRequirement: 19,
    starThresholds: const [5400, 8000, 10000],
    layout: level27Layout,
  ),
  LevelDefinition(
    id: 21,
    name: 'Enduring Chain',
    boardRows: 14,
    boardCols: 12,
    tileCount: 158,
    tileIds: _tileIdsForPairs(79),
    unlockRequirement: 20,
    starThresholds: const [5700, 8400, 10500],
    layout: level28Layout,
  ),
  LevelDefinition(
    id: 22,
    name: 'Complete Heritage',
    boardRows: 14,
    boardCols: 12,
    tileCount: 168,
    tileIds: kTileIds,
    unlockRequirement: 21,
    starThresholds: const [6000, 9000, 11200],
    layout: level29Layout,
  ),
];

LevelDefinition? getLevelById(int id) {
  try {
    return kLevels.firstWhere((l) => l.id == id);
  } catch (_) {
    return null;
  }
}
