import 'layout_data.dart';
import 'level_data.dart';

/// Approved and frozen production source for Chapters 13 and 14.
///
/// [kLevels] assigns these definitions directly, while this retained catalogue
/// keeps the reviewed metadata and stable signatures available to regression
/// tests and production artifact tooling.
class RoadmapLayoutCandidate {
  const RoadmapLayoutCandidate({
    required this.level,
    required this.chapter,
    required this.layout,
    required this.family,
    required this.silhouetteClass,
    required this.proposedName,
    required this.features,
    required this.symbolPlan,
    required this.difficultyCategory,
    required this.fullnessClass,
    required this.isBreather,
    required this.isShowcase,
    required this.isAnchor,
  });

  final int level;
  final int chapter;
  final NamedLayout layout;
  final String family;
  final String silhouetteClass;
  final String proposedName;
  final List<String> features;
  final SymbolCopyPlan symbolPlan;
  final String difficultyCategory;
  final String fullnessClass;
  final bool isBreather;
  final bool isShowcase;
  final bool isAnchor;
}

const Set<int> kLevels241To280Breathers = {
  241,
  246,
  252,
  257,
  263,
  269,
  275,
};

const Set<int> kLevels241To280Showcases = {
  245,
  250,
  255,
  260,
  265,
  270,
  275,
  280,
};

const Set<int> kLevels241To280Finales = {260, 280};

const Set<int> kLevels241To280Anchors = {
  241,
  245,
  250,
  255,
  260,
  261,
  265,
  270,
  275,
  280,
};

NamedLayout _layeredMaskLayout({
  required int level,
  required String idStem,
  required List<String> baseMask,
  required List<String> topMask,
  List<int>? rowOffsets,
  List<int>? rowCoordinates,
  int middleRowOffset = 1,
}) {
  if (baseMask.length != topMask.length) {
    throw ArgumentError('Base and top masks must have equal height.');
  }
  final width = baseMask.fold<int>(
    0,
    (largest, row) => row.length > largest ? row.length : largest,
  );
  final offsets = rowOffsets ?? List<int>.filled(baseMask.length, 0);
  final rows = rowCoordinates ??
      List<int>.generate(baseMask.length, (index) => index * 2);
  if (offsets.length != baseMask.length || rows.length != baseMask.length) {
    throw ArgumentError('Mask metadata height mismatch.');
  }
  final startCol = 16 - (width - 1);
  final base = <TilePosition>[];
  final top = <TilePosition>[];
  for (var rowIndex = 0; rowIndex < baseMask.length; rowIndex++) {
    if (topMask[rowIndex].length != baseMask[rowIndex].length) {
      throw ArgumentError('Top row $rowIndex width mismatch.');
    }
    for (var column = 0; column < baseMask[rowIndex].length; column++) {
      final col = startCol + offsets[rowIndex] + column * 2;
      if (baseMask[rowIndex][column] == 'X') {
        base.add(TilePosition(rows[rowIndex], col, 0));
      }
      if (topMask[rowIndex][column] == 'X') {
        if (baseMask[rowIndex][column] != 'X') {
          throw ArgumentError(
              'Unsupported top mask cell at $rowIndex:$column.');
        }
        top.add(TilePosition(rows[rowIndex], col, 2));
      }
    }
  }
  if (top.isEmpty || top.length.isOdd) {
    throw ArgumentError('Top mask must contain a positive even tile count.');
  }
  return namedLayout(
    'roadmap$level$idStem',
    'Approved Chapter ${level <= 260 ? 13 : 14} production layout',
    [
      ...base,
      for (final tile in base)
        TilePosition(tile.row + middleRowOffset, tile.col, 1),
      ...top,
    ],
  );
}

RoadmapLayoutCandidate _anchor({
  required int level,
  required String idStem,
  required String name,
  required String family,
  required String silhouetteClass,
  required String fullnessClass,
  required List<String> baseMask,
  required List<String> topMask,
  required List<String> features,
  List<int>? rowOffsets,
  List<int>? rowCoordinates,
  int middleRowOffset = 1,
}) =>
    RoadmapLayoutCandidate(
      level: level,
      chapter: level <= 260 ? 13 : 14,
      layout: _layeredMaskLayout(
        level: level,
        idStem: idStem,
        baseMask: baseMask,
        topMask: topMask,
        rowOffsets: rowOffsets,
        rowCoordinates: rowCoordinates,
        middleRowOffset: middleRowOffset,
      ),
      family: family,
      silhouetteClass: silhouetteClass,
      proposedName: name,
      features: List.unmodifiable(features),
      symbolPlan: SymbolCopyPlan(
        symbolPoolSize: level <= 260
            ? 62 + ((level - 241) ~/ 3)
            : 64 + ((level - 261) ~/ 2),
        preferredCopies: 4,
      ),
      difficultyCategory: level <= 260
          ? (level == 241 ? 'Mythic re-entry' : 'Mythic river council')
          : 'Mythic ancestral forest',
      fullnessClass: fullnessClass,
      isBreather: kLevels241To280Breathers.contains(level),
      isShowcase: kLevels241To280Showcases.contains(level),
      isAnchor: true,
    );

RoadmapLayoutCandidate _complement({
  required int level,
  required String idStem,
  required String name,
  required String family,
  required String silhouetteClass,
  required String fullnessClass,
  required List<String> baseMask,
  required List<String> topMask,
  required List<String> features,
  List<int>? rowOffsets,
  List<int>? rowCoordinates,
  int middleRowOffset = 1,
}) =>
    RoadmapLayoutCandidate(
      level: level,
      chapter: level <= 260 ? 13 : 14,
      layout: _layeredMaskLayout(
        level: level,
        idStem: idStem,
        baseMask: baseMask,
        topMask: topMask,
        rowOffsets: rowOffsets,
        rowCoordinates: rowCoordinates,
        middleRowOffset: middleRowOffset,
      ),
      family: family,
      silhouetteClass: silhouetteClass,
      proposedName: name,
      features: List.unmodifiable(features),
      symbolPlan: SymbolCopyPlan(
        symbolPoolSize: level <= 260
            ? 62 + ((level - 241) ~/ 3)
            : 64 + ((level - 261) ~/ 2),
        preferredCopies: 4,
      ),
      difficultyCategory:
          level <= 260 ? 'Mythic river council' : 'Mythic ancestral forest',
      fullnessClass: fullnessClass,
      isBreather: kLevels241To280Breathers.contains(level),
      isShowcase: kLevels241To280Showcases.contains(level),
      isAnchor: false,
    );

/// Stage-A anchors. They establish the river/delta grammar for Chapter 13 and
/// the root/canopy/guardian grammar for Chapter 14 before complements are added.
final List<RoadmapLayoutCandidate> kLevels241To280AnchorCandidates =
    List.unmodifiable([
  _anchor(
    level: 241,
    idStem: 'DeltaWelcome',
    name: 'The River Opens Again',
    family: 'Welcoming delta gate',
    silhouetteClass: 'Open river gate',
    fullnessClass: 'open-medium',
    baseMask: const [
      '.XX.',
      'XXXX',
      'X..X',
      'XX.X',
      'X.XX',
      'X..X',
      'XXXX',
    ],
    topMask: const [
      '.XX.',
      'X..X',
      '....',
      'X...',
      '...X',
      '....',
      'X..X',
    ],
    features: const [
      'broad welcoming delta mouth',
      'large central route opening',
      'light three-layer crown',
    ],
  ),
  _anchor(
    level: 245,
    idStem: 'TwinDeltaShields',
    name: 'Shields of the Twin Current',
    family: 'Twin delta shields',
    silhouetteClass: 'Split guardian masses',
    fullnessClass: 'bulky',
    baseMask: const [
      'XX.XX',
      'XXXXX',
      'X.X.X',
      'XX.XX',
      '.XXX.',
      'X.X.X',
      'XXXXX',
      'XX.XX',
    ],
    topMask: const [
      'XX.XX',
      'X...X',
      '..X..',
      'X...X',
      '.X.X.',
      '....X',
      'X.X..',
      '.X.X.',
    ],
    features: const [
      'paired shield shoulders',
      'offset current windows',
      'stepped river foundation',
    ],
  ),
  _anchor(
    level: 250,
    idStem: 'CouncilBridge',
    name: 'Bridge of Many Voices',
    family: 'Layered council bridge',
    silhouetteClass: 'Bridge and chambers',
    fullnessClass: 'full',
    baseMask: const [
      'XXXX',
      'X.XX',
      'XXXX',
      'X..X',
      'XX.X',
      'XXXX',
      'X.XX',
      'XXXX',
    ],
    topMask: const [
      'X.XX',
      '....',
      'XX.X',
      '....',
      'X...',
      '.XX.',
      '...X',
      'X..X',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0, 1],
    features: const [
      'staggered canoe bridge bars',
      'alternating council chambers',
      'controlled horizontal current',
    ],
  ),
  _anchor(
    level: 255,
    idStem: 'SpiralConfluence',
    name: 'The Turning Confluence',
    family: 'Spiral river sanctuary',
    silhouetteClass: 'Controlled spiral mass',
    fullnessClass: 'bulky',
    baseMask: const [
      '.XXX.',
      'XXXXX',
      'X...X',
      'XXX.X',
      'X.XXX',
      'X...X',
      'XXXXX',
      '.XXX.',
    ],
    topMask: const [
      '.X.X.',
      'X.X.X',
      'X....',
      '..X.X',
      'X.X..',
      '....X',
      'X.X.X',
      '.X.X.',
    ],
    features: const [
      'spiralling centre channel',
      'opposed delta windows',
      'rounded sanctuary crown',
    ],
  ),
  _anchor(
    level: 260,
    idStem: 'RiverCouncilConfluence',
    name: 'The River Council Convenes',
    family: 'River council confluence',
    silhouetteClass: 'Monumental confluence',
    fullnessClass: 'bulky',
    baseMask: const [
      'XXXX',
      'X.XX',
      'XXXX',
      'XX.X',
      'X.XX',
      'XXXX',
      'XX.X',
      'XXXX',
    ],
    topMask: const [
      'X.XX',
      'X.XX',
      'XX.X',
      'XX.X',
      'X.XX',
      'XX.X',
      'XX.X',
      'X.XX',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0, 1],
    features: const [
      'three-stream ceremonial crown',
      'major council entrance',
      'forked middle current',
      'broad confluence foundation',
    ],
  ),
  _anchor(
    level: 261,
    idStem: 'ForestThreshold',
    name: 'Beneath the First Canopy',
    family: 'Forest threshold',
    silhouetteClass: 'Rooted canopy gate',
    fullnessClass: 'full',
    baseMask: const [
      '.XX.',
      'XXXX',
      'X..X',
      'X...',
      'X.XX',
      'X..X',
      'X..X',
      'XXXX',
    ],
    topMask: const [
      '.XX.',
      'XXXX',
      '....',
      'X...',
      'X.XX',
      'X..X',
      'X..X',
      'X..X',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0, 1],
    features: const [
      'high leaf canopy',
      'open vertical forest lane',
      'rooted five-point base',
    ],
  ),
  _anchor(
    level: 265,
    idStem: 'GuardianGrove',
    name: 'Guardians of the Deep Grove',
    family: 'Four guardian grove',
    silhouetteClass: 'Guardian clusters',
    fullnessClass: 'bulky',
    baseMask: const [
      'X.X.X',
      'XXXXX',
      'XX.XX',
      '.XXX.',
      'X.X.X',
      'XX.XX',
      'XXXXX',
      'X.X.X',
    ],
    topMask: const [
      'X...X',
      '.XXX.',
      'X...X',
      '.X.X.',
      '..X..',
      'X...X',
      '.X.X.',
      'X...X',
    ],
    features: const [
      'four guardian shoulder masses',
      'diamond grove chamber',
      'interlocked root foundation',
    ],
  ),
  _anchor(
    level: 270,
    idStem: 'CanopySanctuary',
    name: 'Sanctuary Under Stars',
    family: 'Royal canopy sanctuary',
    silhouetteClass: 'Layered canopy',
    fullnessClass: 'full',
    baseMask: const [
      '.XXX',
      'XXXX',
      'X..X',
      'XX.X',
      'X.XX',
      'X..X',
      'XXXX',
      'XX.X',
    ],
    topMask: const [
      '.X.X',
      'X.X.',
      '....',
      'X..X',
      '..X.',
      'X...',
      '.X.X',
      'X..X',
    ],
    rowOffsets: const [1, 0, 1, 0, 1, 0, 1, 0],
    features: const [
      'offset starlit canopy',
      'deep sanctuary chamber',
      'asymmetric spreading roots',
    ],
  ),
  _anchor(
    level: 275,
    idStem: 'BreathingAncestorCourt',
    name: 'Court of the Listening Trees',
    family: 'Triple ancestor court',
    silhouetteClass: 'Open grove courts',
    fullnessClass: 'open-medium',
    baseMask: const [
      'X.XX',
      'XXXX',
      'X..X',
      'XX.X',
      'X..X',
      'X.XX',
      'XXXX',
    ],
    topMask: const [
      'X.X.',
      '.X.X',
      '....',
      'X...',
      '....',
      '..X.',
      'X..X',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0],
    features: const [
      'three readable court spaces',
      'generous starting branches',
      'showcase detail at breather density',
    ],
  ),
  _anchor(
    level: 280,
    idStem: 'GreatAncestralTree',
    name: 'The Great Ancestral Tree',
    family: 'Great ancestral tree',
    silhouetteClass: 'Monumental tree sanctuary',
    fullnessClass: 'bulky',
    baseMask: const [
      '..X..',
      '.XXX.',
      'XXXXX',
      'XX.XX',
      'XXXXX',
      'X...X',
      'X.X.X',
      'XXXXX',
    ],
    topMask: const [
      '..X..',
      '.XXX.',
      'XXXXX',
      'XX.XX',
      'X...X',
      'X...X',
      'X...X',
      'XXXXX',
    ],
    features: const [
      'distinctive treetop crown',
      'paired guardian boughs',
      'large ceremonial trunk opening',
      'secondary branch windows',
      'broad root sanctuary',
    ],
  ),
]);

/// Stage-B complements, authored only after the anchor grammar passed its
/// structural, envelope, fullness, and coarse-similarity audit.
final List<RoadmapLayoutCandidate> kLevels241To280ComplementCandidates =
    List.unmodifiable([
  _complement(
    level: 242,
    idStem: 'ForkedCurrent',
    name: 'Where the Current Divides',
    family: 'Forked river path',
    silhouetteClass: 'Forked asymmetric channel',
    fullnessClass: 'full',
    baseMask: const [
      'XXX.',
      'XXXX',
      'X.XX',
      'XX.X',
      '.XXX',
      'X.XX',
      'XXXX',
      'XX.X',
    ],
    topMask: const [
      'X.X.',
      'XX.X',
      'X...',
      '.X.X',
      '..XX',
      'X..X',
      '.XX.',
      'X..X',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0, 1],
    middleRowOffset: 0,
    features: const [
      'two readable route branches',
      'alternating current bars',
      'offset lower landing',
    ],
  ),
  _complement(
    level: 243,
    idStem: 'DeltaIslands',
    name: 'Islands of Shared Counsel',
    family: 'Triple delta islands',
    silhouetteClass: 'Connected island masses',
    fullnessClass: 'bulky',
    baseMask: const [
      'X.X.X',
      'XX.XX',
      '.XXX.',
      'X.X.X',
      'XXXXX',
      'XX.XX',
      'X.X.X',
    ],
    topMask: const [
      'X...X',
      '.X.X.',
      '..X..',
      'X...X',
      '.XXX.',
      'X...X',
      'X.X..',
    ],
    rowCoordinates: const [0, 2, 4, 6, 8, 11, 13],
    features: const [
      'three linked island crowns',
      'open water channels',
      'deep delta footing',
    ],
  ),
  _complement(
    level: 244,
    idStem: 'CanoeGate',
    name: 'The Canoe Gate',
    family: 'Canoe-shaped river gate',
    silhouetteClass: 'Tapered bridge gate',
    fullnessClass: 'full',
    baseMask: const [
      '.XX.',
      'XXXX',
      'XX.X',
      'X..X',
      'X.XX',
      'XXXX',
      '.XXX',
    ],
    topMask: const [
      '.XX.',
      'X..X',
      'XX..',
      '....',
      '..XX',
      'X.X.',
      '..XX',
    ],
    rowOffsets: const [1, 0, 1, 0, 1, 0, 1],
    features: const [
      'raised canoe prow',
      'central passage gate',
      'staggered landing steps',
    ],
  ),
  _complement(
    level: 246,
    idStem: 'SteppingStoneCourt',
    name: 'The Gentle Crossing',
    family: 'Stepping-stone court',
    silhouetteClass: 'Open substantial court',
    fullnessClass: 'open-medium',
    baseMask: const [
      'X.XX',
      'XXXX',
      'X..X',
      '.XX.',
      'X..X',
      'XX.X',
      'XXXX',
    ],
    topMask: const [
      'X.X.',
      'X..X',
      '....',
      '.XX.',
      '....',
      'XX..',
      'X..X',
    ],
    rowCoordinates: const [0, 2, 4, 6, 8, 11, 13],
    features: const [
      'quiet stepping-stone centre',
      'low cover density',
      'broad readable banks',
    ],
  ),
  _complement(
    level: 247,
    idStem: 'TwinRiverArches',
    name: 'Arches Over Two Rivers',
    family: 'Twin river arches',
    silhouetteClass: 'Paired arch chambers',
    fullnessClass: 'bulky',
    baseMask: const [
      '.XXX.',
      'XX.XX',
      'X.X.X',
      'XX.XX',
      'X...X',
      'XX.XX',
      'XXXXX',
      '.XXX.',
    ],
    topMask: const [
      '.X.X.',
      'X...X',
      '..X..',
      'X...X',
      '.....',
      'X...X',
      '.XXX.',
      '.X.X.',
    ],
    middleRowOffset: 0,
    features: const [
      'paired upper arches',
      'large shared lower channel',
      'layered bridge crown',
    ],
  ),
  _complement(
    level: 248,
    idStem: 'DiscoveryDelta',
    name: 'Delta of Discovery',
    family: 'Discovery river fan',
    silhouetteClass: 'Fanned asymmetric delta',
    fullnessClass: 'full',
    baseMask: const [
      'XX..',
      'XXXX',
      '.XXX',
      'XX.X',
      'X.XX',
      'XXXX',
      'XXX.',
      'X.XX',
    ],
    topMask: const [
      'XX..',
      'XX..',
      '..XX',
      'XX..',
      '..XX',
      '.X.X',
      'X.X.',
      'X..X',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0, 1],
    middleRowOffset: 0,
    features: const [
      'fan-shaped discovery branches',
      'offset reveal chamber',
      'wide downstream base',
    ],
  ),
  _complement(
    level: 249,
    idStem: 'ReedbankVessel',
    name: 'Vessel Among the Reeds',
    family: 'Sacred river vessel',
    silhouetteClass: 'Vessel and reed shoulders',
    fullnessClass: 'bulky',
    baseMask: const [
      'X...X',
      'XX.XX',
      '.XXX.',
      '..XXX',
      'X.X.X',
      'XX.XX',
      '.XXX.',
    ],
    topMask: const [
      'X...X',
      '.X.X.',
      '..X..',
      '..X.X',
      'X.X..',
      'X...X',
      '.XXX.',
    ],
    rowCoordinates: const [0, 2, 4, 6, 9, 11, 13],
    features: const [
      'high reed guardians',
      'hollow vessel bowl',
      'weighted curved base',
    ],
  ),
  _complement(
    level: 251,
    idStem: 'FourTributaries',
    name: 'Council of Four Tributaries',
    family: 'Four tributary monument',
    silhouetteClass: 'Four-way channel mass',
    fullnessClass: 'bulky',
    baseMask: const [
      'X.X.X',
      'XXXXX',
      '.XXX.',
      '.X.XX',
      'XXXXX',
      'X.X.X',
      'XX.XX',
      'XXXXX',
    ],
    topMask: const [
      'X.X.X',
      '.X.X.',
      '..X..',
      '.X..X',
      'X.X.X',
      '..X..',
      'X...X',
      'XX.XX',
    ],
    middleRowOffset: 0,
    features: const [
      'four directional channels',
      'central council knot',
      'broad tributary base',
    ],
  ),
  _complement(
    level: 252,
    idStem: 'QuietCrossing',
    name: 'Still Water Crossing',
    family: 'Quiet river crossing',
    silhouetteClass: 'Open bridge breather',
    fullnessClass: 'open-medium',
    baseMask: const [
      '.XX.',
      'XXXX',
      'X..X',
      'XX.X',
      'X..X',
      'X.XX',
      'XXXX',
    ],
    topMask: const [
      '.XX.',
      '.XX.',
      '....',
      'XX..',
      '....',
      '..XX',
      'X..X',
    ],
    features: const [
      'single calm central opening',
      'simple supported bridge bars',
      'generous exposed banks',
    ],
  ),
  _complement(
    level: 253,
    idStem: 'RiverKey',
    name: 'Key of the Returning River',
    family: 'Royal river key',
    silhouetteClass: 'Keyed asymmetric monument',
    fullnessClass: 'full',
    baseMask: const [
      'XXX.',
      'XXXX',
      'X.XX',
      '.XXX',
      'XX.X',
      'XXXX',
      'X.XX',
      'XXX.',
    ],
    topMask: const [
      'X.X.',
      'XX.X',
      'X..X',
      '..XX',
      'X...',
      '.XX.',
      'X..X',
      'XX..',
    ],
    rowOffsets: const [1, 0, 1, 0, 1, 0, 1, 0],
    middleRowOffset: 0,
    features: const [
      'rotated key crown',
      'offset lock chamber',
      'stepped river teeth',
    ],
  ),
  _complement(
    level: 254,
    idStem: 'OpenDeltaShrine',
    name: 'Shrine of Open Water',
    family: 'Open delta shrine',
    silhouetteClass: 'Tall open shrine',
    fullnessClass: 'open-medium',
    baseMask: const [
      '.XX.',
      'XXXX',
      'X..X',
      'X.XX',
      'X..X',
      'XX.X',
      'X..X',
      'XXXX',
    ],
    topMask: const [
      '.XX.',
      'X..X',
      '....',
      '..XX',
      '....',
      'XX..',
      '....',
      'X..X',
    ],
    features: const [
      'tall ceremonial water opening',
      'light shrine cap',
      'substantial four-wide base',
    ],
  ),
  _complement(
    level: 256,
    idStem: 'CouncilDrum',
    name: 'Drum of the River Council',
    family: 'Sacred council drum',
    silhouetteClass: 'Layered drum formation',
    fullnessClass: 'full',
    baseMask: const [
      '.XXX',
      'XXXX',
      'XX.X',
      'X.XX',
      'XXXX',
      'X..X',
      'XXXX',
    ],
    topMask: const [
      '.X.X',
      'X.X.',
      'X...',
      '..XX',
      '.XX.',
      'X...',
      'X..X',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0],
    features: const [
      'rhythmic alternating bands',
      'open drum chamber',
      'weighted sounding base',
    ],
  ),
  _complement(
    level: 257,
    idStem: 'StillwaterCourt',
    name: 'Court Beside Still Water',
    family: 'Stillwater courtyard',
    silhouetteClass: 'Open offset court',
    fullnessClass: 'open-medium',
    baseMask: const [
      'XX.X',
      'XXXX',
      'X..X',
      '.XX.',
      'X..X',
      'X.XX',
      'XXXX',
    ],
    topMask: const [
      'X..X',
      '.XX.',
      '....',
      '.XX.',
      '....',
      '..XX',
      'X..X',
    ],
    rowCoordinates: const [0, 2, 4, 7, 9, 11, 13],
    features: const [
      'broad stillwater courtyard',
      'two quiet side landings',
      'low-pressure top layer',
    ],
  ),
  _complement(
    level: 258,
    idStem: 'WingedCanoeMonument',
    name: 'The Winged Canoe',
    family: 'Winged canoe monument',
    silhouetteClass: 'Winged central vessel',
    fullnessClass: 'bulky',
    baseMask: const [
      'X.X.X',
      'XX.XX',
      'XXXXX',
      '.XXX.',
      'X.X.X',
      'XX.XX',
      '.XXX.',
      'XXXXX',
    ],
    topMask: const [
      'X...X',
      'XX.XX',
      '.XX..',
      '.X.X.',
      'X...X',
      'X...X',
      '.X.X.',
      'XX.XX',
    ],
    middleRowOffset: 0,
    features: const [
      'unfurled canoe wings',
      'raised central prow',
      'split waterline openings',
    ],
  ),
  _complement(
    level: 259,
    idStem: 'ConfluenceThreshold',
    name: 'Threshold of the Confluence',
    family: 'Confluence threshold',
    silhouetteClass: 'Stepped river threshold',
    fullnessClass: 'full',
    baseMask: const [
      'XXXXX',
      'XXXX.',
      'XX...',
      'XXX.X',
      'XX...',
      'XXXX.',
      'XXXXX',
    ],
    topMask: const [
      'X.X.X',
      'XXX..',
      'XX...',
      'XX..X',
      'X....',
      'XXX..',
      'X.X.X',
    ],
    rowCoordinates: const [0, 2, 4, 6, 8, 11, 13],
    features: const [
      'rising confluence threshold',
      'paired route-choice windows',
      'dense but narrower pre-finale mass',
    ],
  ),
  _complement(
    level: 262,
    idStem: 'GuardianRoots',
    name: 'Roots of the Watchful Ones',
    family: 'Guardian root fortress',
    silhouetteClass: 'Rooted guardian masses',
    fullnessClass: 'bulky',
    baseMask: const [
      'X.X.X',
      'XX.XX',
      'XXXXX',
      'X.X.X',
      '.XXX.',
      'XX.XX',
      'X.X.X',
      'XXXXX',
    ],
    topMask: const [
      'X...X',
      'X...X',
      '.XXX.',
      'X.X..',
      '.X.X.',
      'X...X',
      '..X..',
      'XX.XX',
    ],
    middleRowOffset: 0,
    features: const [
      'watchful root shoulders',
      'central guardian eye',
      'interwoven lower roots',
    ],
  ),
  _complement(
    level: 263,
    idStem: 'FirstLightClearing',
    name: 'Clearing of First Light',
    family: 'Forest light clearing',
    silhouetteClass: 'Open canopy clearing',
    fullnessClass: 'open-medium',
    baseMask: const [
      '.XX.',
      'XXXX',
      'X..X',
      'XX.X',
      'X..X',
      '.XXX',
      'XXXX',
    ],
    topMask: const [
      '.XX.',
      'X..X',
      '....',
      'XX..',
      '....',
      '..XX',
      '.XX.',
    ],
    rowCoordinates: const [0, 2, 4, 6, 9, 11, 13],
    features: const [
      'large sunlit clearing',
      'light leaf canopy',
      'full lower grove footing',
    ],
  ),
  _complement(
    level: 264,
    idStem: 'TwinCanopyArches',
    name: 'Arches Beneath the Canopy',
    family: 'Twin canopy arches',
    silhouetteClass: 'Staggered forest arches',
    fullnessClass: 'full',
    baseMask: const [
      'XX.X',
      'XX.X',
      'X.XX',
      'X..X',
      '.XXX',
      'X..X',
      'X.XX',
      'X.XX',
    ],
    topMask: const [
      'X..X',
      'XX.X',
      'X...',
      '....',
      '..XX',
      'X..X',
      'X.X.',
      'X..X',
    ],
    rowOffsets: const [1, 0, 1, 0, 1, 0, 1, 0],
    middleRowOffset: 0,
    features: const [
      'paired offset canopy arches',
      'open vertical breathing lanes',
      'root bridge foundation',
    ],
  ),
  _complement(
    level: 266,
    idStem: 'CrownedForestMask',
    name: 'Mask of the Crowned Forest',
    family: 'Crowned forest mask',
    silhouetteClass: 'Mask and canopy crown',
    fullnessClass: 'bulky',
    baseMask: const [
      '.XXX.',
      'XXXXX',
      'X.X.X',
      'XX.XX',
      'XXXXX',
      'X...X',
      'XX.XX',
      '.XXX.',
    ],
    topMask: const [
      '.XXX.',
      'X.X.X',
      'X.X..',
      'X...X',
      '.X.X.',
      'X...X',
      '.X.X.',
      '.X.X.',
    ],
    middleRowOffset: 0,
    features: const [
      'three-point leaf crown',
      'paired mask eyes',
      'open mouth chamber',
    ],
  ),
  _complement(
    level: 267,
    idStem: 'RootBridge',
    name: 'Bridge of Living Roots',
    family: 'Layered root bridge',
    silhouetteClass: 'Root bridge channels',
    fullnessClass: 'full',
    baseMask: const [
      'XXX.',
      'XXXX',
      'X.XX',
      'XX.X',
      'XXXX',
      '.XXX',
      'XX.X',
    ],
    topMask: const [
      'X.X.',
      'XX.X',
      'X..X',
      '.X.X',
      'X.X.',
      '..XX',
      'X...',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0],
    features: const [
      'braided root bridge',
      'alternating underpass gaps',
      'stepped woodland banks',
    ],
  ),
  _complement(
    level: 268,
    idStem: 'TreeOfNewMemory',
    name: 'Tree of New Memory',
    family: 'Memory-bearing tree',
    silhouetteClass: 'Branched memory tree',
    fullnessClass: 'bulky',
    baseMask: const [
      '..X..',
      '.XXX.',
      'XX.XX',
      'XXXXX',
      'X.X.X',
      '.XXX.',
      'XX.XX',
      'XXXXX',
    ],
    topMask: const [
      '..X..',
      '.X.X.',
      'X...X',
      '.XXX.',
      'X.X..',
      '.X.X.',
      'X...X',
      'XX.XX',
    ],
    middleRowOffset: 0,
    features: const [
      'single rising memory branch',
      'paired bough chambers',
      'broad mnemonic roots',
    ],
  ),
  _complement(
    level: 269,
    idStem: 'QuietGrove',
    name: 'The Quiet Grove',
    family: 'Quiet ancestor grove',
    silhouetteClass: 'Open rooted grove',
    fullnessClass: 'open-medium',
    baseMask: const [
      'XX.X',
      'XXXX',
      'X..X',
      'X.XX',
      'X..X',
      '.XXX',
      'XXXX',
    ],
    topMask: const [
      'X..X',
      '.XX.',
      '....',
      '..XX',
      '....',
      '.X.X',
      'X..X',
    ],
    rowCoordinates: const [0, 2, 5, 7, 9, 11, 13],
    features: const [
      'wide quiet grove opening',
      'few covered branches',
      'substantial rooted base',
    ],
  ),
  _complement(
    level: 271,
    idStem: 'GrandTurtleGrove',
    name: 'The Great Turtle Grove',
    family: 'Grand forest turtle',
    silhouetteClass: 'Animal guardian mass',
    fullnessClass: 'bulky',
    baseMask: const [
      '.XXX.',
      'X.X.X',
      'XXXXX',
      'XX.XX',
      'XXXXX',
      'X.X.X',
      'XX.XX',
    ],
    topMask: const [
      '.X.X.',
      'X...X',
      '.XXX.',
      'X...X',
      'X.X.X',
      'X.X..',
      'X...X',
    ],
    rowCoordinates: const [0, 2, 4, 6, 8, 11, 13],
    features: const [
      'arched guardian shell',
      'four grounded limbs',
      'open heart of the grove',
    ],
  ),
  _complement(
    level: 272,
    idStem: 'OpenTempleLeaves',
    name: 'Temple of Falling Leaves',
    family: 'Open leaf temple',
    silhouetteClass: 'Tall temple clearing',
    fullnessClass: 'open-medium',
    baseMask: const [
      'X.XX',
      'XXXX',
      'X..X',
      '.XX.',
      'X..X',
      'XX.X',
      'X..X',
      'XXXX',
    ],
    topMask: const [
      'X.X.',
      '.XX.',
      '....',
      '.XX.',
      '....',
      'XX..',
      '....',
      'X..X',
    ],
    features: const [
      'tall leaf-fall chamber',
      'split temple cap',
      'clear processional base',
    ],
  ),
  _complement(
    level: 273,
    idStem: 'TwinSacredVessels',
    name: 'Vessels of the Elder Grove',
    family: 'Twin sacred vessels',
    silhouetteClass: 'Paired vessel chambers',
    fullnessClass: 'full',
    baseMask: const [
      'XX.X',
      'XXXX',
      'X.XX',
      'XX.X',
      '.XXX',
      'X.XX',
      'XXXX',
      'XX.X',
    ],
    topMask: const [
      'X..X',
      'X.X.',
      'X..X',
      '.X.X',
      '..XX',
      'X..X',
      '.XX.',
      'XX..',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0, 1],
    middleRowOffset: 0,
    features: const [
      'paired vessel bowls',
      'offset pouring channels',
      'shared ceremonial footing',
    ],
  ),
  _complement(
    level: 274,
    idStem: 'AncestralCrossroads',
    name: 'Crossroads of the Ancestors',
    family: 'Ancestral forest cross',
    silhouetteClass: 'Crossed guardian paths',
    fullnessClass: 'bulky',
    baseMask: const [
      '..X..',
      'XX.X.',
      'XXXXX',
      '.XXX.',
      'XXXXX',
      'X.XX.',
      'XXXXX',
    ],
    topMask: const [
      '..X..',
      'XX.X.',
      'X.X.X',
      '.X.X.',
      'X.X.X',
      'X..X.',
      'XX.XX',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0],
    features: const [
      'four ancestral routes',
      'layered crossing chamber',
      'weighted path foundation',
    ],
  ),
  _complement(
    level: 276,
    idStem: 'WingedThroneTree',
    name: 'Throne of the Winged Tree',
    family: 'Winged tree throne',
    silhouetteClass: 'Asymmetric canopy throne',
    fullnessClass: 'full',
    baseMask: const [
      'XXX.',
      'XXXX',
      '.XXX',
      'X..X',
      '.XXX',
      'XXXX',
      'X.XX',
      'XXXX',
    ],
    topMask: const [
      'X.X.',
      'XX.X',
      '..XX',
      'X...',
      '..XX',
      '.XX.',
      'X..X',
      'X.X.',
    ],
    rowOffsets: const [1, 0, 1, 0, 1, 0, 1, 0],
    middleRowOffset: 0,
    features: const [
      'one raised canopy wing',
      'hollow throne seat',
      'layered root dais',
    ],
  ),
  _complement(
    level: 277,
    idStem: 'FourRootsFortress',
    name: 'Fortress of Four Roots',
    family: 'Four-root guardian fortress',
    silhouetteClass: 'Hollow forest fortress',
    fullnessClass: 'bulky',
    baseMask: const [
      'XX.XX',
      'XXXXX',
      'X...X',
      'XX.XX',
      'X.X.X',
      'XX.XX',
      'XXXXX',
      'X.X.X',
    ],
    topMask: const [
      'X...X',
      'XX.XX',
      '.....',
      'X...X',
      '..X..',
      'X...X',
      '.XXX.',
      'X...X',
    ],
    features: const [
      'four rooted corner towers',
      'large fortress courtyard',
      'layered defensive canopy',
    ],
  ),
  _complement(
    level: 278,
    idStem: 'ReturningNamesGrove',
    name: 'Grove of Returning Names',
    family: 'Memory-name grove',
    silhouetteClass: 'Staggered memorial grove',
    fullnessClass: 'full',
    baseMask: const [
      'XX..',
      'XX.X',
      'X.XX',
      '.XXX',
      'XX.X',
      'X.XX',
      '.XXX',
      'XX.X',
    ],
    topMask: const [
      'XX..',
      'XX..',
      'X...',
      '..XX',
      'X..X',
      '..XX',
      '..XX',
      'X...',
    ],
    rowOffsets: const [0, 1, 0, 1, 0, 1, 0, 1],
    features: const [
      'staggered memorial branches',
      'name-tablet windows',
      'returning root path',
    ],
  ),
  _complement(
    level: 279,
    idStem: 'GuardiansBeforeDawn',
    name: 'Guardians Before Dawn',
    family: 'Dawn guardian towers',
    silhouetteClass: 'Twin tower approach',
    fullnessClass: 'bulky',
    baseMask: const [
      'X...X',
      'XX.XX',
      'XXXXX',
      'X.X.X',
      '.XXX.',
      'XX.XX',
      'X.X.X',
      'XXXXX',
    ],
    topMask: const [
      'X...X',
      'X...X',
      '.XXX.',
      'X...X',
      '.X.X.',
      'X...X',
      '..X..',
      'XX.XX',
    ],
    features: const [
      'twin dawn watchtowers',
      'central approach opening',
      'broad pre-finale root base',
    ],
  ),
]);

final List<RoadmapLayoutCandidate> kLevels241To280Candidates =
    List.unmodifiable([
  ...kLevels241To280AnchorCandidates,
  ...kLevels241To280ComplementCandidates,
]..sort((first, second) => first.level.compareTo(second.level)));
