enum TileSuit { wisdom, earth, royalty, honor }

class TileDefinition {
  final String id;
  final String name;
  final String meaning;
  final String symbol;
  final TileSuit suit;
  final int suitNumber;
  final String? assetPath;

  const TileDefinition({
    required this.id,
    required this.name,
    required this.meaning,
    required this.symbol,
    required this.suit,
    required this.suitNumber,
    this.assetPath,
  });
}

const List<String> kTileIds = [
  'aban',
  'abe_dua',
  'abode_santann',
  'abusua_pa',
  'adinkrahene',
  'agyindawuru',
  'akoben',
  'denkyem',
  'dwennimmen',
  'gye_nyame',
  'nea_onnim',
  'nkyinkyim',
  'nsoromma',
  'odo_nnyew_fie_kwan',
  'akoma',
  'akoma_ntoaso',
  'ananse_ntentan',
  'ani_bere_a_enso_gya',
  'anyi_me_aye_a',
  'aponkyerene_wu_a',
  'asaawa',
  'asae_ye_duru',
  'asetena_pa',
  'aya',
  'bese_saka',
  'bi_nka_bi',
  'boa_me_na_me_mmoa_wo',
  'boafo_ye_na',
  'dame_dame',
  'dono',
  'dono_ntoaso',
  'duafe',
  'dwantire',
  'eban',
  'akofena',
  'akoko_nan',
  'funtumfunefu_denkyemfunefu',
  'sankofa2',
  'fawohodie',
  'fafanto',
  'fihankra',
  'fofo',
  'epa',
  'ese_ne_tekrema',
  'esono_anatam',
  'gyamu_atiko',
  'hwehwemudua',
  'hye_wo_nhye',
  'kete_pa',
  'kokuromotie',
  'kramo_bone_amma_yeanhu_kramo_pa',
  'krapa',
  'kuronti_ne_akwamu',
  'kyemfere',
  'mako',
  'mate_masie',
  'mekyea_wo',
  'menso_wo_kenten',
  'mframadan',
  'mmeramubere',
  'mmeramutene',
  'mmere_dane',
  'mpatapo',
  'mpuannum',
  'nea_oretwa_sa',
  'neo_ope_se_obedi_hene',
  'nkonsonkonson',
  'nkotimsefo_mpua',
  'nkrabea',
  'nkyemu',
  'nnamfo_pa_baanu',
  'nsaa',
  'nserewa',
  'nteasee',
  'nyame_baatanpa',
  'nyame_biribi_wo_soro',
  'nyame_dua',
  'nyame_nti',
  'nyame_nwa_na_mawu',
  'nyansapo',
  'obohemaa',
  'okodee_mmowere',
  'okuafo_pa',
  'osram_ne_nsoromma',
];

const List<TileDefinition> kAllTiles = [
  TileDefinition(
    id: 'aban',
    name: 'Aban',
    meaning: 'The castle - authority',
    symbol: 'A',
    suit: TileSuit.royalty,
    suitNumber: 1,
    assetPath: 'assets/Tile V2 png/aban-removebg-preview.png',
  ),
  TileDefinition(
    id: 'abe_dua',
    name: 'Abe Dua',
    meaning: 'Palm tree',
    symbol: 'P',
    suit: TileSuit.earth,
    suitNumber: 1,
    assetPath: 'assets/Tile V2 png/abe_dua-removebg-preview.png',
  ),
  TileDefinition(
    id: 'abode_santann',
    name: 'Abode Santann',
    meaning: 'The cosmos - universe',
    symbol: 'C',
    suit: TileSuit.honor,
    suitNumber: 1,
    assetPath: 'assets/Tile V2 png/abode_santann-removebg-preview.png',
  ),
  TileDefinition(
    id: 'abusua_pa',
    name: 'Abusua Pa',
    meaning: 'Good family',
    symbol: 'F',
    suit: TileSuit.honor,
    suitNumber: 2,
    assetPath: 'assets/Tile V2 png/abusua_pa_-removebg-preview.png',
  ),
  TileDefinition(
    id: 'adinkrahene',
    name: 'Adinkrahene',
    meaning: 'Chief of Adinkra',
    symbol: 'K',
    suit: TileSuit.royalty,
    suitNumber: 2,
    assetPath: 'assets/Tile V2 png/adinkrahene-removebg-preview.png',
  ),
  TileDefinition(
    id: 'agyindawuru',
    name: 'Agyindawuru',
    meaning: 'The gong - warning',
    symbol: 'G',
    suit: TileSuit.honor,
    suitNumber: 3,
    assetPath: 'assets/Tile V2 png/agyin_dawuru-removebg-preview.png',
  ),
  TileDefinition(
    id: 'akoben',
    name: 'Akoben',
    meaning: 'War horn - readiness',
    symbol: 'H',
    suit: TileSuit.honor,
    suitNumber: 4,
    assetPath: 'assets/Tile V2 png/akoben-removebg-preview.png',
  ),
  TileDefinition(
    id: 'denkyem',
    name: 'Denkyem',
    meaning: 'Adaptability',
    symbol: 'D',
    suit: TileSuit.earth,
    suitNumber: 2,
    assetPath: 'assets/Tile V2 png/denkyem-removebg-preview.png',
  ),
  TileDefinition(
    id: 'dwennimmen',
    name: 'Dwennimmen',
    meaning: 'Strength with humility',
    symbol: 'S',
    suit: TileSuit.honor,
    suitNumber: 5,
    assetPath: 'assets/Tile V2 png/dwennimmen-removebg-preview.png',
  ),
  TileDefinition(
    id: 'gye_nyame',
    name: 'Gye Nyame',
    meaning: 'Except God',
    symbol: 'G',
    suit: TileSuit.honor,
    suitNumber: 6,
    assetPath: 'assets/Tile V2 png/gye_nyame-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nea_onnim',
    name: 'Nea Onnim',
    meaning: 'He who does not know',
    symbol: '?',
    suit: TileSuit.wisdom,
    suitNumber: 1,
    assetPath: 'assets/Tile V2 png/nea_onnim-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nkyinkyim',
    name: 'Nkyinkyim',
    meaning: 'Adaptability',
    symbol: 'N',
    suit: TileSuit.wisdom,
    suitNumber: 2,
    assetPath: 'assets/Tile V2 png/nkyinkyim-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nsoromma',
    name: 'Nsoromma',
    meaning: 'Star - child of the heavens',
    symbol: '*',
    suit: TileSuit.honor,
    suitNumber: 7,
    assetPath: 'assets/Tile V2 png/nsoromma-removebg-preview.png',
  ),
  TileDefinition(
    id: 'odo_nnyew_fie_kwan',
    name: 'Odo Nnyew Fie Kwan',
    meaning: 'Love never loses its way home',
    symbol: 'O',
    suit: TileSuit.honor,
    suitNumber: 8,
    assetPath: 'assets/Tile V2 png/odo_nnyew_fie_kwan-removebg-preview.png',
  ),
  TileDefinition(
    id: 'akoma',
    name: 'Akoma',
    meaning: 'Heart - patience and tolerance',
    symbol: 'A',
    suit: TileSuit.honor,
    suitNumber: 9,
    assetPath: 'assets/Tile V2 png.2/akoma-removebg-preview.png',
  ),
  TileDefinition(
    id: 'akoma_ntoaso',
    name: 'Akoma Ntoaso',
    meaning: 'Linked hearts - understanding',
    symbol: 'L',
    suit: TileSuit.honor,
    suitNumber: 10,
    assetPath: 'assets/Tile V2 png.2/akoma_ntoaso-removebg-preview.png',
  ),
  TileDefinition(
    id: 'akofena',
    name: 'Akofena',
    meaning: 'Sword of war - courage and valor',
    symbol: 'K',
    suit: TileSuit.royalty,
    suitNumber: 5,
    assetPath: 'assets/Tile V2 png/akofena-removebg-preview.png',
  ),
  TileDefinition(
    id: 'akoko_nan',
    name: 'Akoko Nan',
    meaning: 'Hen leg - nurture and discipline',
    symbol: 'N',
    suit: TileSuit.earth,
    suitNumber: 7,
    assetPath: 'assets/Tile V2 png/akoko_nan-removebg-preview.png',
  ),
  TileDefinition(
    id: 'ananse_ntentan',
    name: 'Ananse Ntentan',
    meaning: 'Spider web - wisdom and creativity',
    symbol: 'W',
    suit: TileSuit.wisdom,
    suitNumber: 3,
    assetPath: 'assets/Tile V2 png.2/ananse_ntentan-removebg-preview.png',
  ),
  TileDefinition(
    id: 'ani_bere_a_enso_gya',
    name: 'Ani Bere A Enso Gya',
    meaning: 'Watchfulness and restraint',
    symbol: 'E',
    suit: TileSuit.wisdom,
    suitNumber: 4,
    assetPath: 'assets/Tile V2 png.2/ani_bere_a_enso_gya-removebg-preview.png',
  ),
  TileDefinition(
    id: 'anyi_me_aye_a',
    name: 'Anyi Me Aye A',
    meaning: 'Perseverance through hardship',
    symbol: 'Y',
    suit: TileSuit.honor,
    suitNumber: 11,
    assetPath: 'assets/Tile V2 png.2/anyi_me_aye_a-removebg-preview.png',
  ),
  TileDefinition(
    id: 'aponkyerene_wu_a',
    name: 'Aponkyerene Wu A',
    meaning: 'Resilience and renewal',
    symbol: 'R',
    suit: TileSuit.earth,
    suitNumber: 3,
    assetPath: 'assets/Tile V2 png.2/aponkyerene_wu_a-removebg-preview.png',
  ),
  TileDefinition(
    id: 'asaawa',
    name: 'Asaawa',
    meaning: 'Elegance and adornment',
    symbol: 'S',
    suit: TileSuit.honor,
    suitNumber: 12,
    assetPath: 'assets/Tile V2 png.2/asaawa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'asae_ye_duru',
    name: 'Asase Ye Duru',
    meaning: 'The earth has weight',
    symbol: 'E',
    suit: TileSuit.earth,
    suitNumber: 4,
    assetPath: 'assets/Tile V2 png.2/asae_ye_duru-removebg-preview.png',
  ),
  TileDefinition(
    id: 'asetena_pa',
    name: 'Asetena Pa',
    meaning: 'Good living and wellbeing',
    symbol: 'P',
    suit: TileSuit.honor,
    suitNumber: 13,
    assetPath: 'assets/Tile V2 png.2/asetena_pa_-removebg-preview.png',
  ),
  TileDefinition(
    id: 'aya',
    name: 'Aya',
    meaning: 'Endurance and resourcefulness',
    symbol: 'A',
    suit: TileSuit.earth,
    suitNumber: 5,
    assetPath: 'assets/Tile V2 png.2/aya-removebg-preview.png',
  ),
  TileDefinition(
    id: 'bese_saka',
    name: 'Bese Saka',
    meaning: 'Abundance and unity',
    symbol: 'B',
    suit: TileSuit.earth,
    suitNumber: 6,
    assetPath: 'assets/Tile V2 png.2/bese_saka-removebg-preview.png',
  ),
  TileDefinition(
    id: 'bi_nka_bi',
    name: 'Bi Nka Bi',
    meaning: 'Peace and harmony',
    symbol: 'B',
    suit: TileSuit.honor,
    suitNumber: 14,
    assetPath: 'assets/Tile V2 png.2/bi_nka_bi-removebg-preview.png',
  ),
  TileDefinition(
    id: 'boa_me_na_me_mmoa_wo',
    name: 'Boa Me Na Me Mmoa Wo',
    meaning: 'Help me and let me help you',
    symbol: 'M',
    suit: TileSuit.honor,
    suitNumber: 15,
    assetPath: 'assets/Tile V2 png.2/boa_me_na_me_mmoa_wo-removebg-preview.png',
  ),
  TileDefinition(
    id: 'boafo_ye_na',
    name: 'Boafo Ye Na',
    meaning: 'A helper is precious',
    symbol: 'F',
    suit: TileSuit.honor,
    suitNumber: 16,
    assetPath: 'assets/Tile V2 png.2/boafo_ye_na-removebg-preview.png',
  ),
  TileDefinition(
    id: 'dame_dame',
    name: 'Dame Dame',
    meaning: 'Strategy and intelligence',
    symbol: 'D',
    suit: TileSuit.wisdom,
    suitNumber: 5,
    assetPath: 'assets/Tile V2 png.2/dame_dame_-removebg-preview.png',
  ),
  TileDefinition(
    id: 'dono',
    name: 'Dono',
    meaning: 'Talking drum - communication',
    symbol: 'D',
    suit: TileSuit.honor,
    suitNumber: 17,
    assetPath: 'assets/Tile V2 png.2/dono-removebg-preview.png',
  ),
  TileDefinition(
    id: 'dono_ntoaso',
    name: 'Dono Ntoaso',
    meaning: 'Drum link - shared message',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 18,
    assetPath: 'assets/Tile V2 png.2/dono_ntoaso-removebg-preview.png',
  ),
  TileDefinition(
    id: 'duafe',
    name: 'Duafe',
    meaning: 'Beauty and care',
    symbol: 'U',
    suit: TileSuit.honor,
    suitNumber: 19,
    assetPath: 'assets/Tile V2 png.2/duafe-removebg-preview.png',
  ),
  TileDefinition(
    id: 'dwantire',
    name: 'Dwantire',
    meaning: 'Leadership and protection',
    symbol: 'T',
    suit: TileSuit.royalty,
    suitNumber: 3,
    assetPath: 'assets/Tile V2 png.2/dwantire-removebg-preview.png',
  ),
  TileDefinition(
    id: 'eban',
    name: 'Eban',
    meaning: 'Fence - safety and love',
    symbol: 'E',
    suit: TileSuit.royalty,
    suitNumber: 4,
    assetPath: 'assets/Tile V2 png.2/eban-removebg-preview.png',
  ),
  TileDefinition(
    id: 'fawohodie',
    name: 'Fawohodie',
    meaning: 'Independence and freedom',
    symbol: 'F',
    suit: TileSuit.honor,
    suitNumber: 20,
    assetPath: 'assets/Tile v.3 png/fawohodie-removebg-preview.png',
  ),
  TileDefinition(
    id: 'fafanto',
    name: 'Fafanto',
    meaning: 'Butterfly - tenderness and transformation',
    symbol: 'F',
    suit: TileSuit.earth,
    suitNumber: 8,
    assetPath: 'assets/Tile v.3 png/fafanto-removebg-preview.png',
  ),
  TileDefinition(
    id: 'fihankra',
    name: 'Fihankra',
    meaning: 'Compound house - safety and fellowship',
    symbol: 'H',
    suit: TileSuit.honor,
    suitNumber: 21,
    assetPath: 'assets/Tile v.3 png/fihankra-removebg-preview.png',
  ),
  TileDefinition(
    id: 'fofo',
    name: 'Fofo',
    meaning: 'Warning against envy',
    symbol: 'V',
    suit: TileSuit.wisdom,
    suitNumber: 6,
    assetPath: 'assets/Tile v.3 png/fofo-removebg-preview.png',
  ),
  TileDefinition(
    id: 'funtumfunefu_denkyemfunefu',
    name: 'Funtumfunefu Denkyemfunefu',
    meaning: 'Unity in diversity',
    symbol: 'U',
    suit: TileSuit.honor,
    suitNumber: 22,
    assetPath:
        'assets/Tile V2 png/funtumfunefu_denkyemfunefu-removebg-preview.png',
  ),
  TileDefinition(
    id: 'epa',
    name: 'Epa',
    meaning: 'Law, justice, and restraint',
    symbol: 'J',
    suit: TileSuit.royalty,
    suitNumber: 6,
    assetPath: 'assets/Tile v.3 png/epa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'ese_ne_tekrema',
    name: 'Ese Ne Tekrema',
    meaning: 'Teeth and tongue - friendship and interdependence',
    symbol: 'T',
    suit: TileSuit.honor,
    suitNumber: 23,
    assetPath: 'assets/Tile v.3 png/ese_ne_tekrema-removebg-preview.png',
  ),
  TileDefinition(
    id: 'esono_anatam',
    name: 'Esono Anatam',
    meaning: 'Elephant footprint - leadership and impact',
    symbol: 'I',
    suit: TileSuit.royalty,
    suitNumber: 7,
    assetPath: 'assets/Tile v.3 png/esono_anatam-removebg-preview.png',
  ),
  TileDefinition(
    id: 'gyamu_atiko',
    name: 'Gyamu Atiko',
    meaning: 'Bravery and readiness',
    symbol: 'Y',
    suit: TileSuit.royalty,
    suitNumber: 8,
    assetPath: 'assets/Tile v.3 png/gyamu_atiko-removebg-preview.png',
  ),
  TileDefinition(
    id: 'hwehwemudua',
    name: 'Hwehwemudua',
    meaning: 'Measuring rod - excellence and examination',
    symbol: 'X',
    suit: TileSuit.wisdom,
    suitNumber: 7,
    assetPath: 'assets/Tile v.3 png/hwehwemudua-removebg-preview.png',
  ),
  TileDefinition(
    id: 'hye_wo_nhye',
    name: 'Hye Wo Nhye',
    meaning: 'That which does not burn',
    symbol: 'R',
    suit: TileSuit.honor,
    suitNumber: 24,
    assetPath: 'assets/Tile v.3 png/hye_wo_nhye-removebg-preview.png',
  ),
  TileDefinition(
    id: 'kete_pa',
    name: 'Kete Pa',
    meaning: 'Good bed - good marriage',
    symbol: 'Q',
    suit: TileSuit.honor,
    suitNumber: 25,
    assetPath: 'assets/Tile v.3 png/kete_pa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'kokuromotie',
    name: 'Kokuromotie',
    meaning: 'Thumb - cooperation and service',
    symbol: 'K',
    suit: TileSuit.honor,
    suitNumber: 26,
    assetPath: 'assets/Tile v.3 png/kokuromotie-removebg-preview.png',
  ),
  TileDefinition(
    id: 'kramo_bone_amma_yeanhu_kramo_pa',
    name: 'Kramo Bone Amma Yeanhu Kramo Pa',
    meaning: 'Discernment and caution',
    symbol: 'C',
    suit: TileSuit.wisdom,
    suitNumber: 8,
    assetPath:
        'assets/Tile v.3 png/kramo_bone_amma_yeanhu_kramo_pa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'sankofa2',
    name: 'Sankofa',
    meaning: 'Return and retrieve what was left behind',
    symbol: 'S',
    suit: TileSuit.wisdom,
    suitNumber: 9,
    assetPath: 'assets/Tile V2 png/sankofa2-removebg-preview.png',
  ),
  TileDefinition(
    id: 'krapa',
    name: 'Krapa',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'K',
    suit: TileSuit.wisdom,
    suitNumber: 10,
    assetPath: 'assets/Tile v.4 png/krapa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'kuronti_ne_akwamu',
    name: 'Kuronti Ne Akwamu',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'K',
    suit: TileSuit.royalty,
    suitNumber: 9,
    assetPath: 'assets/Tile v.4 png/kuronti_ne_akwamu-removebg-preview.png',
  ),
  TileDefinition(
    id: 'kyemfere',
    name: 'Kyemfere',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'K',
    suit: TileSuit.earth,
    suitNumber: 9,
    assetPath: 'assets/Tile v.4 png/kyemfere-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mako',
    name: 'Mako',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.earth,
    suitNumber: 10,
    assetPath: 'assets/Tile v.4 png/mako-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mate_masie',
    name: 'Mate Masie',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.wisdom,
    suitNumber: 11,
    assetPath: 'assets/Tile v.4 png/mate_masie-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mekyea_wo',
    name: 'Mekyea Wo',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.honor,
    suitNumber: 27,
    assetPath: 'assets/Tile v.4 png/mekyea_wo-removebg-preview.png',
  ),
  TileDefinition(
    id: 'menso_wo_kenten',
    name: 'Menso Wo Kenten',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.honor,
    suitNumber: 28,
    assetPath: 'assets/Tile v.4 png/menso_wo_kenten-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mframadan',
    name: 'Mframadan',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.earth,
    suitNumber: 11,
    assetPath: 'assets/Tile v.4 png/mframadan-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mmeramubere',
    name: 'Mmeramubere',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.wisdom,
    suitNumber: 12,
    assetPath: 'assets/Tile v.4 png/mmeramubere-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mmeramutene',
    name: 'Mmeramutene',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.honor,
    suitNumber: 29,
    assetPath: 'assets/Tile v.4 png/mmeramutene-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mmere_dane',
    name: 'Mmere Dane',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.wisdom,
    suitNumber: 13,
    assetPath: 'assets/Tile v.4 png/mmere_dane-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mpatapo',
    name: 'Mpatapo',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.honor,
    suitNumber: 30,
    assetPath: 'assets/Tile v.4 png/mpatapo-removebg-preview.png',
  ),
  TileDefinition(
    id: 'mpuannum',
    name: 'Mpuannum',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'M',
    suit: TileSuit.honor,
    suitNumber: 31,
    assetPath: 'assets/Tile v.4 png/mpuannum-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nea_oretwa_sa',
    name: 'Nea Oretwa Sa',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.wisdom,
    suitNumber: 14,
    assetPath: 'assets/Tile v.4 png/nea_oretwa_sa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'neo_ope_se_obedi_hene',
    name: 'Neo Ope Se Obedi Hene',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.royalty,
    suitNumber: 10,
    assetPath: 'assets/Tile v.4 png/neo_ope_se_obedi_hene-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nkonsonkonson',
    name: 'Nkonsonkonson',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 32,
    assetPath: 'assets/Tile v.4 png/nkonsonkonson-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nkotimsefo_mpua',
    name: 'Nkotimsefo Mpua',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.royalty,
    suitNumber: 11,
    assetPath: 'assets/Tile v.4 png/nkotimsefo_mpua-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nkrabea',
    name: 'Nkrabea',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.wisdom,
    suitNumber: 15,
    assetPath: 'assets/Tile v.4 png/nkrabea-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nkyemu',
    name: 'Nkyemu',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.wisdom,
    suitNumber: 16,
    assetPath: 'assets/Tile v.4 png/nkyemu-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nnamfo_pa_baanu',
    name: 'Nnamfo Pa Baanu',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 33,
    assetPath: 'assets/Tile v.4 png/nnamfo_pa_baanu-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nsaa',
    name: 'Nsaa',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 34,
    assetPath: 'assets/Tile v.4 png/nsaa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nserewa',
    name: 'Nserewa',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 35,
    assetPath: 'assets/Tile v.4 png/nserewa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nteasee',
    name: 'Nteasee',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 36,
    assetPath: 'assets/Tile v.4 png/nteasee-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nyame_baatanpa',
    name: 'Nyame Baatanpa',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 37,
    assetPath: 'assets/Tile v.4 png/nyame_baatanpa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nyame_biribi_wo_soro',
    name: 'Nyame Biribi Wo Soro',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 38,
    assetPath: 'assets/Tile v.4 png/nyame_biribi_wo_soro-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nyame_dua',
    name: 'Nyame Dua',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 39,
    assetPath: 'assets/Tile v.4 png/nyame_dua-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nyame_nti',
    name: 'Nyame Nti',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 40,
    assetPath: 'assets/Tile v.4 png/nyame_nti-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nyame_nwa_na_mawu',
    name: 'Nyame Nwa Na Mawu',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.honor,
    suitNumber: 41,
    assetPath: 'assets/Tile v.4 png/nyame_nwa_na_mawu-removebg-preview.png',
  ),
  TileDefinition(
    id: 'nyansapo',
    name: 'Nyansapo',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'N',
    suit: TileSuit.wisdom,
    suitNumber: 17,
    assetPath: 'assets/Tile v.4 png/nyansapo-removebg-preview.png',
  ),
  TileDefinition(
    id: 'obohemaa',
    name: 'Obohemaa',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'O',
    suit: TileSuit.royalty,
    suitNumber: 12,
    assetPath: 'assets/Tile v.4 png/obohemaa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'okodee_mmowere',
    name: 'Okodee Mmowere',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'O',
    suit: TileSuit.royalty,
    suitNumber: 13,
    assetPath: 'assets/Tile v.4 png/okodee_mmowere-removebg-preview.png',
  ),
  TileDefinition(
    id: 'okuafo_pa',
    name: 'Okuafo Pa',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'O',
    suit: TileSuit.earth,
    suitNumber: 12,
    assetPath: 'assets/Tile v.4 png/okuafo_pa-removebg-preview.png',
  ),
  TileDefinition(
    id: 'osram_ne_nsoromma',
    name: 'Osram Ne Nsoromma',
    meaning: 'Traditional Adinkra symbol',
    symbol: 'O',
    suit: TileSuit.honor,
    suitNumber: 42,
    assetPath: 'assets/Tile v.4 png/osram_ne_nsoromma-removebg-preview.png',
  ),
];
